#!/usr/bin/env bash
composer() {
  COMPOSER_HOME=${COMPOSER_HOME:-$HOME/.composer}
  local tty=
  local CONTAINER_IMAGE=${COMPOSER_IMAGE:-composer}
  local CONTAINER_OPTIONS=""

  tty -s && tty=--tty

  docker run \
    --rm \
    --interactive \
    $tty \
    --env SSH_AUTH_SOCK=/ssh-auth.sock \
    --volume /etc/passwd:/etc/passwd:ro \
    --volume /etc/group:/etc/group:ro \
    --volume "$(pwd)":/app \
    --volume "$SSH_AUTH_SOCK":/ssh-auth.sock \
    --volume "$COMPOSER_HOME":/composer \
    --user "$(id -u)":"$(id -g)" \
    $CONTAINER_OPTIONS \
    "$CONTAINER_IMAGE" "$@"
}
