#!/usr/bin/env bash
export SYMFONY_ENV=${SYMFONY_ENV:-dev}
export SYMFONY_ASSETS_INSTALL=${SYMFONY_ASSETS_INSTALL:-relative}

sf() {
  ARGS="$@"
  GIT_ROOT=$(git rev-parse --show-toplevel 2>/dev/null)
  CONSOLE=$(git ls-files $GIT_ROOT/**/{app,bin}/console 2>/dev/null | head -n1)

  if [ -z "$CONSOLE" ]; then
    return 1;
  fi

  docker_compose_wrapper php -d memory_limit=-1 ${CONSOLE} ${ARGS}
  return $?
}

phpunit() {
  docker_compose_wrapper php -d memory_limit=-1 bin/phpunit $@
  local status=$?
  if { [ "$status" = "1" ] || [ "$status" = "2" ]; }; then
    command phpunit $@
  fi
  return $status
}
